#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [1]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [ ]:
help(np.add)

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [19]:
x=np.zeros(10)
x[5]=1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [22]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [47]:
x=np.arange(0,51)
-np.sort(-x)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [38]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի ինդեքսները:

In [82]:
arr = np.array([1,2,0,0,4,0])
print(np.where(arr!=0))

(array([0, 1, 4]),)


#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [56]:
np.random.randint(1,20,(3,3,3))

array([[[14, 17,  9],
        [ 6,  5, 19],
        [ 3, 16, 10]],

       [[ 7, 14,  4],
        [ 9, 14, 15],
        [18, 13, 18]],

       [[ 3,  5,  4],
        [ 5, 15, 16],
        [11, 15, 11]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [70]:
a = np.random.randint(0,100,(10,10))
print(a)
print(np.amin(a))
print(np.amax(a))

[[ 6  5 95 48 17 93  4 20 14 45]
 [44 57 34 25 34 46 47 19 59 40]
 [89 18 23 89 38 55 27 61 75 22]
 [74 12 12 95 20 26 56 17 47 71]
 [18 94 25  6  4 82 85 81 23 29]
 [31 27 90 16 88 71 49 76 42 70]
 [87 52  4 66 88 13 24 25 70 12]
 [68 99  2 20 34 61 70 23 35  7]
 [33 41  7 92 44 53 73 46 91 43]
 [50 35 67 12 90 42 85 29 64 85]]
2
99


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [86]:
b = np.random.randint(0,30,30)
print(b)
print(np.mean(b))

[25 26 10  6  8  7  4  3 10  7 24 11 17  0 11 26 20 17  1 15  0 26 21  1
 10 18 15 11  8 18]
12.533333333333333


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [93]:
x = np.arange(11)
y = slice(3,9)
print(x[y])

[3 4 5 6 7 8]


#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [132]:
arr1=np.random.randint(1,10,20)
print(arr1)
arr2 = arr1[arr1<5]
print(arr2)

[2*i for i in arr2]

[3 1 2 2 4 8 2 9 4 8 8 1 9 8 2 6 1 4 4 5]
[3 1 2 2 4 2 4 1 2 1 4 4]


[6, 2, 4, 4, 8, 4, 8, 2, 4, 2, 8, 8]

#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [111]:
a = np.array([1,5,6,2,-2,23,45])
b = np.where(a%2==0)
print(b)

(array([2, 3, 4]),)


#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [119]:
a = np.arange(1,21)
print(a)
print(a[a%3==0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]


#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [142]:
a=np.arange(0,5)
np.tile(a,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 17. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in the array.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի մեծագույն ու փոքրագույն արժեքները։

In [146]:
a = np.array([[0,1], [2,3]])
print(np.amin(a))
print(np.amax(a))

0
3


#### 18. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in each column.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի սյուների մեծագույն ու փոքրագույն արժեքները։

In [164]:
a = np.array([[0,1], [2,3]])
print(a)
print("Minimum values of each column:")
print(np.amin(a,0))
print("Maximum values of each column:")
print(np.amax(a,0))

[[0 1]
 [2 3]]
Minimum values of each column:
[0 1]
Maximum values of each column:
[2 3]


#### 19. Create  numpy array of size 10 filled with integers of your choice. Compute mean, median, standard deviation and variance of the array values. 

#### Ստեղծեք 10 չափանի numpy array, հաշվեք array-ի mean, median, standard deviation և variance։

In [183]:
arr1 = np.random.randint(1,100, 10)
print(arr1)
print("mean:",np.mean(arr1))
print("median:",np.median(arr1))
print("standard deviation:",np.std(arr1))
print("variance:",np.var(arr1))

[82 59 69 78 55  6 48 10  8 43]
mean: 45.8
median: 51.5
standard deviation: 27.29761894378336
variance: 745.1600000000001


#### 20. Calculate the weighted average of the following array: np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]) using weights np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]). 

#### Հաշվեք տրված array-ի կշռված միջինը՝ np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])` օգտագործելով np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) weight-երը։

In [185]:
a = np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])
wts = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.average(a, weights = wts)

13.654545454545454

#### 21. Sort the rows of the following numpy array in an increasing order: np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]). 

#### Աճման կարգով դասավորեք տրված numpy array-ի տողերը՝ np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]):

In [194]:
a = np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]])
print(a)
print("\n Sorted by raws:")
print (np.sort(a, axis = 1)) 

[[4 2 6 1]
 [0 2 6 1]
 [4 4 1 9]]

 Sorted by raws:
[[1 2 4 6]
 [0 1 2 6]
 [1 4 4 9]]


#### 22. Create the following numpy arrays and calculate the dot product between a and b. 

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։

$$a = \begin{bmatrix} 3 & 6 & 7 \\ 5 & -3 & 0  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [218]:
a = np.array([[3,6,7],[5,-3,0]])
b = np.array([[1,1],[2,1],[3,-3]])
print("a:\n", a)
print("b:\n", b)
print("dot product:\n", np.dot(a,b))

a:
 [[ 3  6  7]
 [ 5 -3  0]]
b:
 [[ 1  1]
 [ 2  1]
 [ 3 -3]]
dot product:
 [[ 36 -12]
 [ -1   2]]
